"""empty message

Revision ID: d3d0fce8d46a
Revises: 64f5b057ed18
Create Date: 2022-06-24 17:39:22.921283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d0fce8d46a'
down_revision = '64f5b057ed18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
